info:
  contact: {}
paths:
  /v1/api/log:
    post:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Log
      tags:
      - log
  /v1/api/log/:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get all
      tags:
      - log
  /v1/api/log/{id}:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get log by id
      tags:
      - log
  /v1/api/status:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Status
      tags:
      - log
swagger: "2.0"
